version: "3"

services:
  cassandra:
    image: cassandra:4.0.5 # Also update app/src/test/community/flock/pragmatic/app/environment/Variables.kt
    hostname: cassandra
    container_name: cassandra
    ports:
      - "9142:9042"
    volumes:
      - "./.database:/custom-init"
    working_dir: "/custom-init"
    command: "sh db-init.sh"
    healthcheck:
      test: [ "CMD", "/opt/cassandra/bin/cqlsh", "-u cassandra", "-p cassandra" ,"-e \"describe keyspaces\"" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=local
