###
GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/users/cf8c1fe6-fb9e-436f-883f-cf5ffba90629

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Luke",
  "lastName": "Skywalker",
  "birthDay": "1950-01-01"
}

###
DELETE http://localhost:8080/api/users/4423290e-865a-4c9a-8901-232e6b7053dd
