spring:
  cassandra:
    config: classpath:application.conf
    contact-points: 127.0.0.1
    keyspace-name: pragmatic
    local-datacenter: datacenter1
    username: cassandra
    password: cassandra
    port: 9142
    ssl.enabled: false
    request:
      consistency: one
      serial-consistency: one
